// <auto-generated />
using System;
using HarryPotterAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarryPotterAPI.Migrations
{
    [DbContext(typeof(HarryPotterContext))]
    [Migration("20231127193228_wand")]
    partial class wand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HarryPotterAPI.Models.CharacterModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("House")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("wandid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("wandid");

                    b.ToTable("characters");
                });

            modelBuilder.Entity("HarryPotterAPI.Models.WandModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Core")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Size")
                        .HasColumnType("double");

                    b.Property<string>("Wood")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("wand");
                });

            modelBuilder.Entity("HarryPotterAPI.Models.CharacterModel", b =>
                {
                    b.HasOne("HarryPotterAPI.Models.WandModel", "wand")
                        .WithMany()
                        .HasForeignKey("wandid");

                    b.Navigation("wand");
                });
#pragma warning restore 612, 618
        }
    }
}
